name: linkchat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: 2.1.1
  flutter_screenutil: 5.8.4
  lottie: 2.4.0
  cached_network_image: 3.2.3
  timeago: 3.5.0
  flutter_chat_bubble: 2.0.2
  flutter_webrtc: 0.9.35
  font_awesome_flutter: 10.5.0
  flutter_webrtc_wrapper: 1.0.2
  permission_handler: 10.3.0
  country_picker: 2.0.20
  gzx_dropdown_menu: 3.1.0
  animated_text_kit: 4.2.2
  objectbox: 2.1.0
  objectbox_flutter_libs: 2.1.0
  icon_badge: 1.0.0
  flutter_dtmf: 2.0.2
  flutter_masked_text2: 0.9.1
  image_picker: 0.8.9
  pinput: 2.2.31
  star_menu: 3.1.4
  logger: 1.4.0
  image_cropper: any
  loading_animation_widget: 1.2.0+4
  http: any
  geolocator: 9.0.2
  geocoding: 2.1.0
  path_provider: 2.0.15
  path: 1.8.3
  shimmer: 3.0.0
  intl: 0.18.1
  getwidget: 3.1.1
  dio: 5.3.0
  socket_io_client: 2.0.3+1
  custom_refresh_indicator: 2.2.1
  readmore: 2.2.0
  audioplayers: 5.1.0
  flutter_local_notifications: 15.1.1
  flutter_staggered_grid_view: 0.7.0
  faker: 2.1.0
  uuid: 3.0.7
  googleapis: 11.4.0
  googleapis_auth: 1.4.1
  url_launcher: 6.1.14
  file_picker: 5.5.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: 2.4.6
  objectbox_generator: 2.1.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/anim/
    - assets/images/
    - assets/sounds/
  uses-material-design: true

